type: ACTION
action-type: CHANGECONTROL_CUSTOM
language: PYTHON_3
name: SWAG Image Sync
description: Syncs the specified SWI and the boot-config across all the members, saves the config on the supervisor and reboots all the members other than the supervisor
file: script.py
static-params: []
dynamic-params:
  - name: Source
    description: The name of the SWI to sync
    required: true
    hidden: false
  - name: DeviceID
    description: The ID of the device to run this script against
    required: true
    hidden: false