type: ACTION
name: Generate Campus Node IDs
description: Autofill Campus Studio Node IDs
language: PYTHON_3
action-type: STUDIO_AUTOFILL
file: script.py
static-params: []
dynamic-params:
- name: StudioID
  description: ""
  required: true
  hidden: false
  default: ""
- name: InputPath
  description: ""
  required: true
  hidden: false
  default: ""
- name: WorkspaceID
  description: ""
  required: true
  hidden: false
  default: ""
args: {}
